version: "3.4"

services:
  highscoreapi:
    image: schoeni/highscoreapi
    ports:
      - "5000:5000"
  game:
    build: ..\ts-space-shooter-starter/
    depends_on:
      - highscoreapi
    links:
      - highscoreapi
    ports:
      - "8080:80"
